### ISSUE TITLE
Call to maintainer!

### ISSUE THREAD

**Issue by Typositoire** [Typositoire/concourse-helm3-resource#102]
With the extra work I'm putting into lots of stuff and other things it is clear that I can't maintain this to a level I'm happy with. I'd like to call for a new maintainer. Please manifest yourself!

**Comment by Tang8330** [comment]
@Typositoire Want to chat here? I'm happy to help be one of the maintainers of this project. Our [company](https://artie.so) uses this Concourse resource to upgrade our Helm charts across all of our data planes.

**Comment by Typositoire** [comment]
Man... My notifications suck lol I didn't get this one :/ I'll give you some access, normally I merge everything that makes sense and I follow semver for versioning, fix = patch, new feature = minor and if we ever rewrite anything that would be a major bump.

Everything should be handled by my own concourse, I'll check how I can give you safely access at some point.

**Comment by Typositoire** [comment]
I invited you as a collaborator, not sure that exactly this gives you for permission let me know if you have enough to merge stuff (create a dumb PR)

Feel free to reach me on my social (see my profit)
