### ISSUE TITLE
Add --insecure-skip-tls-verify

### ISSUE THREAD

**Issue by spiderwomn69** [Typositoire/concourse-helm3-resource#11]
Rather than requiring cluster_ca for https can we add the --insecure-skip-tls-verify flag to the resource config?

**Comment by Typositoire** [comment]
indeed I could add that. I'll try to find some time today.

**Comment by Typositoire** [comment]
Can you check the PR to make sure I understood correctly ?

**Comment by spiderwomn69** [comment]
This looks good! Thank you for your quick response!

**Comment by Typositoire** [comment]
Merged and tagged as `v1.3.0` should be in Docker Hub soon-ish
