### ISSUE TITLE
Option to run helm install only (without helm upgrade)

### ISSUE THREAD

**Issue by jackievirgo** [Typositoire/concourse-helm3-resource#14]
I have found an issue in helm where I get this error with the `helm upgrade --install` command:

> coalesce.go:196: warning: cannot overwrite table with non table for defaultNodeSelector (map[])
> coalesce.go:122: Conflict: cannot merge map onto non-map for "defaultNodeSelector". Skipping.
> .
> .
> .
> coalesce.go:196: warning: cannot overwrite table with non table for defaultNodeSelector (map[])
> coalesce.go:133: key defaultNodeSelector is table. Skipping

The full command being run:

> Running command helm upgrade --install istio /tmp/build/put/istio-repo/ci/helm-charts/istio --namespace=istio-system -f /tmp/build/put/istio-repo/ci/helm-charts/istio/values-istio-dev.yaml --set-string global.defaultNodeSelector="my-node-string" | tee /tmp/log

I have found if I run the command as helm install only, it works:

> helm install istio /tmp/build/put/istio-repo/ci/helm-charts/istio --namespace=istio-system -f /tmp/build/put/istio-repo/ci/helm-charts/istio/values-istio-dev.yaml --set-string global.defaultNodeSelector."my-node-sting" | tee /tmp/log

Is there a way to add an option to run `helm install` rather than `helm upgrade --install`?

**Comment by Typositoire** [comment]
Hum I'm really curious to understand WHY because install and ugprade are basically the same... and as far as I know install can't work passed the first install no ?

**Comment by Typositoire** [comment]
As for your question it's not possible right now.

**Comment by spiderwomn69** [comment]
> Hum I'm really curious to understand WHY because install and ugprade are basically the same... and as far as I know install can't work passed the first install no ?

That is an excellent question and it took me awhile to find this was my issue. Unfortunately I have limited permissions for troubleshooting and to get to this point I had to intercept the job and try things in the container.

**Comment by Typositoire** [comment]
ok I'll try and do some debug this weekend.
