### ISSUE TITLE
Remove purge option when deleting a chart as helm3 does it by default and include namespace.

### ISSUE THREAD

**Issue by erathinam** [Typositoire/concourse-helm3-resource#17]
Hi,
     Creating this issue to fix two things.
       1) Helm 3 removed the option of purging a delete and now it is done by default. 
       ISSUE: https://github.com/helm/helm/issues/5804.
      2) Also, since the releases can be installed in different namespaces, `helm delete` should take the namespace as a flag else it won't find it cause it checks the `default` namespace.
      These two fixes requires changing the `out.sh` and README.md.

@Typositoire I would be happy to contribute to this by creating a PR. :) Let me know your thoughts. Great work!!

**Comment by Typositoire** [comment]
PR away! ;-)

**Comment by Typositoire** [comment]
Confinement is really hard for me lots of stuff and less time to do work on my own with kids 24/7 at home ! All help is welcome!

**Comment by erathinam** [comment]
No problem. Il Start working on this and create a PR. :)
