### ISSUE TITLE
Deployment fails without release name

### ISSUE THREAD

**Issue by netcho** [Typositoire/concourse-helm3-resource#25]
A deployment fails without specifying a release name. This is to the fact that Helm3 requires the --generate-name flag to be set IF the name of the release is omitted. Currently the flag ISN'T set if the release is empty

**Comment by Typositoire** [comment]
You are right! Would you be comfortable opening a PR for that ?

**Comment by vvvictor07** [comment]
I think that this issue can be closed. Am I right?

**Comment by Typositoire** [comment]
Yes, thanks for your contribution! @vvvictor07
