### ISSUE TITLE
Gcloud auth implementation

### ISSUE THREAD

**Issue by space55** [Typositoire/concourse-helm3-resource#29]
Hiya,

I just had a quick feature request. I use Google Cloud Platform to host Kubernetes (GKE), and the typical way to authenticate is via the gcloud command. There is an active PR for the Linkyard resource to add the functionality: https://github.com/linkyard/concourse-helm-resource/pull/145

Would there be any possibility of including this in the resource? I'd be happy to PR the changes with @shashankkoppar's permission

Thanks!

**Comment by Typositoire** [comment]
Sorry I'm on vacation :P I will be looking at everything tomorrow! Sorry for the delays!

**Comment by space55** [comment]
No worries at all. Take your time on vacation - we all need one at the moment!

**Comment by shashankkoppar** [comment]
Sure @space55 , no issues! I am already using it in my concourse pipelines and it works fine with both gcloud and certificates authentication.

**Comment by Typositoire** [comment]
Sorry about the delays, so yes now that @shashankkoppar has given his approval, I'd say go for it! I'm barely just back from vacations so I won't have time to do it myself this week.

**Comment by shashankkoppar** [comment]
@Typositoire , I have updated PR to include gcloud auth! Please check when you have time! https://github.com/Typositoire/concourse-helm3-resource/pull/58

**Comment by Typositoire** [comment]
This has been implemented.
