### ISSUE TITLE
Helm Initializing Error

### ISSUE THREAD

**Issue by jackievirgo** [Typositoire/concourse-helm3-resource#51]
Not sure if anyone else has seen this but getting this error when trying to deploy:

> Initializing helm...
> 09:01:15
> version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", > GoVersion:"go1.13.5"}
> 09:01:16
> Error: looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: > failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden

I have tried setting stable_repo to false and get this error and this worked for our on-prem Kubernetes deploy, however it did not work in EKS. I have tried setting stable_repos to the default https://charts.helm.sh/stable but that also does not work. I can add the stable repo if I highjack the container. I am not using "https://kubernetes-charts.storage.googleapis.com" in any of my code but I also don't see anywhere it used anywhere here. 

The last successful deploy in EKS was the first week of December and I have made no changes to my pipeline in that time.

**Comment by Typositoire** [comment]
The error leads me to think you are running an old version which points to the now dead repo and doesn't support `stable_repos`. What version are you using?

**Comment by Typositoire** [comment]
```
After Nov 13, 2020 - Downloads of Charts at their old locations will be re-directed to the read-only archive available in GitHub Pages. The old locations may no longer be available after this date.
RECOMMENDED ACTION - See info on switching to the archived stable and incubator charts. Keep in mind that these charts will no longer be updated with bug fixes or security patches.
```

Ref: https://helm.sh/blog/charts-repo-deprecation/#:~:text=Back%20in%202019%2C%20when%20the,upkeep%20for%20the%20repo%20maintainers.

**Comment by jackievirgo** [comment]
Yep, I was able to find where this is pulling an old version. Thanks for the help!

**Comment by Typositoire** [comment]
No problems!
