### ISSUE TITLE
Unable to connect to the server: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by MaheshBGajera** [Typositoire/concourse-helm3-resource#83]
Starting v1.22.0, this resource check started failing with error: **Unable to connect to the server: x509: certificate signed by unknown authority**

Concourse Version: 7.1.1
Concourse Worker OS: Ubuntu 20.4 LTS

If I downgrade to version v1.21.0, I get following error:
**/opt/resource/common.sh: line 43: /dev/stderr: Permission denied**
and if I set privileged=true on resource type, it works.

**Comment by Typositoire** [comment]
The only thing I can see is the helm version that is different between 1.22.0 and 1.21.0. What was the last version you used that worked?

**Comment by moojigc** [comment]
Hello, is this issue resolved? I started seeing this error yesterday, even with a base64 cert on version 1.25.0.
