### ISSUE TITLE
Concourse in Kubernetes support

### ISSUE THREAD

**Issue by adamfowleruk** [Typositoire/concourse-helm3-resource#88]
Hello. Looks like a great resource. Slight hiccough I had was getting this working on a Concourse worker that is installed in Kubernetes itself. In this scenario, although I can point token_path at /var/run/secrets/kubernetes.io/serviceaccount/token, there is no way to provide ca path rather than ca value.

Given that Kubernetes service accounts have all the info to talk to the API server, it would be great if an example can be added and tested of a working K8S helm3 install. 

FYI I'm trying this on EKS with Concourse installed via its own helm chart, and installing a custom helm chart in a separate namespace on the same demonstration K8S cluster.

Happy to discuss this and to work on it myself. I've reached out to you on the Concourse Discord too to discuss options.

Thanks!

**Comment by adamfowleruk** [comment]
Here's my Concourse output where this failed:-

```
Initializing kubectl using certificates

Cluster "default" set.

User "admin" set.

Context "default" created.

Switched to context "default".

E1206 15:01:44.341386      69 cert_rotation.go:168] key failed with : tls: failed to find any PEM data in certificate input

E1206 15:01:44.347337      69 cert_rotation.go:168] key failed with : tls: failed to find any PEM data in certificate input

E1206 15:01:44.357601      69 cert_rotation.go:168] key failed with : tls: failed to find any PEM data in certificate input

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

Unable to connect to the server: tls: failed to find any PEM data in certificate input
```

And here's the relevant parts of my pipeline config:-
```yaml
resource_types:
- name: helm
  type: docker-image
  source:
    repository: ghcr.io/typositoire/concourse-helm3-resource

resources:
- name: demo-helm-deploy
  type: helm
  source:
    release: rover
    namespace: rover-demo
    cluster_url: https://kubernetes.default.svc
    token_path: /var/run/secrets/kubernetes.io/serviceaccount/token
    # I CANNOT PASS A PATH TO THE ca.crt FILE IN THE SAME FOLDER AS THE ABOVE TOKEN
    # AS THE HELM3 RESOURCE DOESN'T SUPPORT THIS
    cluster_ca_base64: ((cluster-ca-base64)) 
    insecure_cluster: true
...
jobs:
# Deploy the demo to the rover-demo namespace in K8S
- name: deploy-demo
  public: false
  serial: true
  plan:
  - get: rover-helm-chart
    trigger: true
    params: {depth: 1}
  - get: rover-demo-helm-config
    trigger: true
    params: {depth: 1}
  - put: demo-helm-deploy
    params:
      chart: rover-helm-chart/rover
      values: rover-demo-helm-config/demo-shared-env/rover-demo-values.yaml
```

**Comment by Tang8330** [comment]
@adamfowleruk in case you're still trying this.

I had this problem this weekend and modified this repo to work w/ EKS. PR: https://github.com/Typositoire/concourse-helm3-resource/pull/97

Docker link https://hub.docker.com/r/artielabs/concourse-helm3

**Comment by Tang8330** [comment]
This is now supported.
